# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Z:/EENG498/Lab_4/acquireToHDMI.xdc

# IP: ip/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet
